import BgVideo from "@/components/BgVideo";

export default function Home() {
  return (
    <div className="relative top-0 backdrop:blur-sm width-full h-full  bg-opacity-80">
      <div className="felx flex-cal h-[850px] gap-20">
      <BgVideo />
      </div>
      <section className="text-md">
        <p>
          Lorem ipsum dolor sit amet consectetur adipisicing elit. Commodi, tempora molestiae cum voluptatem voluptates facere sequi laudantium consequatur hic consequuntur nulla recusandae explicabo quae atque, dolores aliquid tenetur reprehenderit nemo.
          Lorem ipsum dolor sit amet consectetur adipisicing elit. Commodi, tempora molestiae cum voluptatem voluptates facere sequi laudantium consequatur hic consequuntur nulla recusandae explicabo quae atque, dolores aliquid tenetur reprehenderit nemo.
          Lorem ipsum dolor sit amet consectetur adipisicing elit. Commodi, tempora molestiae cum voluptatem voluptates facere sequi laudantium consequatur hic consequuntur nulla recusandae explicabo quae atque, dolores aliquid tenetur reprehenderit nemo.
          Lorem ipsum dolor sit amet consectetur adipisicing elit. Commodi, tempora molestiae cum voluptatem voluptates facere sequi laudantium consequatur hic consequuntur nulla recusandae explicabo quae atque, dolores aliquid tenetur reprehenderit nemo.
          Lorem ipsum dolor sit amet consectetur adipisicing elit. Commodi, tempora molestiae cum voluptatem voluptates facere sequi laudantium consequatur hic consequuntur nulla recusandae explicabo quae atque, dolores aliquid tenetur reprehenderit nemo.
          Lorem ipsum dolor sit amet consectetur adipisicing elit. Commodi, tempora molestiae cum voluptatem voluptates facere sequi laudantium consequatur hic consequuntur nulla recusandae explicabo quae atque, dolores aliquid tenetur reprehenderit nemo.
          Lorem ipsum dolor sit amet consectetur adipisicing elit. Commodi, tempora molestiae cum voluptatem voluptates facere sequi laudantium consequatur hic consequuntur nulla recusandae explicabo quae atque, dolores aliquid tenetur reprehenderit nemo.
          Lorem ipsum dolor sit amet consectetur adipisicing elit. Commodi, tempora molestiae cum voluptatem voluptates facere sequi laudantium consequatur hic consequuntur nulla recusandae explicabo quae atque, dolores aliquid tenetur reprehenderit nemo.
          Lorem ipsum dolor sit amet consectetur adipisicing elit. Commodi, tempora molestiae cum voluptatem voluptates facere sequi laudantium consequatur hic consequuntur nulla recusandae explicabo quae atque, dolores aliquid tenetur reprehenderit nemo.
          Lorem ipsum dolor sit amet consectetur adipisicing elit. Commodi, tempora molestiae cum voluptatem voluptates facere sequi laudantium consequatur hic consequuntur nulla recusandae explicabo quae atque, dolores aliquid tenetur reprehenderit nemo.
          Lorem ipsum dolor sit amet consectetur adipisicing elit. Commodi, tempora molestiae cum voluptatem voluptates facere sequi laudantium consequatur hic consequuntur nulla recusandae explicabo quae atque, dolores aliquid tenetur reprehenderit nemo.
          Lorem ipsum dolor sit amet consectetur adipisicing elit. Commodi, tempora molestiae cum voluptatem voluptates facere sequi laudantium consequatur hic consequuntur nulla recusandae explicabo quae atque, dolores aliquid tenetur reprehenderit nemo.
          Lorem ipsum dolor sit amet consectetur adipisicing elit. Commodi, tempora molestiae cum voluptatem voluptates facere sequi laudantium consequatur hic consequuntur nulla recusandae explicabo quae atque, dolores aliquid tenetur reprehenderit nemo.
          Lorem ipsum dolor sit amet consectetur adipisicing elit. Commodi, tempora molestiae cum voluptatem voluptates facere sequi laudantium consequatur hic consequuntur nulla recusandae explicabo quae atque, dolores aliquid tenetur reprehenderit nemo.
          Lorem ipsum dolor sit amet consectetur adipisicing elit. Commodi, tempora molestiae cum voluptatem voluptates facere sequi laudantium consequatur hic consequuntur nulla recusandae explicabo quae atque, dolores aliquid tenetur reprehenderit nemo.
          Lorem ipsum dolor sit amet consectetur adipisicing elit. Commodi, tempora molestiae cum voluptatem voluptates facere sequi laudantium consequatur hic consequuntur nulla recusandae explicabo quae atque, dolores aliquid tenetur reprehenderit nemo.
          Lorem ipsum dolor sit amet consectetur adipisicing elit. Commodi, tempora molestiae cum voluptatem voluptates facere sequi laudantium consequatur hic consequuntur nulla recusandae explicabo quae atque, dolores aliquid tenetur reprehenderit nemo.
          Lorem ipsum dolor sit amet consectetur adipisicing elit. Commodi, tempora molestiae cum voluptatem voluptates facere sequi laudantium consequatur hic consequuntur nulla recusandae explicabo quae atque, dolores aliquid tenetur reprehenderit nemo.
          Lorem ipsum dolor sit amet consectetur adipisicing elit. Commodi, tempora molestiae cum voluptatem voluptates facere sequi laudantium consequatur hic consequuntur nulla recusandae explicabo quae atque, dolores aliquid tenetur reprehenderit nemo.
          Lorem ipsum dolor sit amet consectetur adipisicing elit. Commodi, tempora molestiae cum voluptatem voluptates facere sequi laudantium consequatur hic consequuntur nulla recusandae explicabo quae atque, dolores aliquid tenetur reprehenderit nemo.
          Lorem ipsum dolor sit amet consectetur adipisicing elit. Commodi, tempora molestiae cum voluptatem voluptates facere sequi laudantium consequatur hic consequuntur nulla recusandae explicabo quae atque, dolores aliquid tenetur reprehenderit nemo.
          Lorem ipsum dolor sit amet consectetur adipisicing elit. Commodi, tempora molestiae cum voluptatem voluptates facere sequi laudantium consequatur hic consequuntur nulla recusandae explicabo quae atque, dolores aliquid tenetur reprehenderit nemo.
          Lorem ipsum dolor sit amet consectetur adipisicing elit. Commodi, tempora molestiae cum voluptatem voluptates facere sequi laudantium consequatur hic consequuntur nulla recusandae explicabo quae atque, dolores aliquid tenetur reprehenderit nemo.
          Lorem ipsum dolor sit amet consectetur adipisicing elit. Commodi, tempora molestiae cum voluptatem voluptates facere sequi laudantium consequatur hic consequuntur nulla recusandae explicabo quae atque, dolores aliquid tenetur reprehenderit nemo.
          Lorem ipsum dolor sit amet consectetur adipisicing elit. Commodi, tempora molestiae cum voluptatem voluptates facere sequi laudantium consequatur hic consequuntur nulla recusandae explicabo quae atque, dolores aliquid tenetur reprehenderit nemo.
          Lorem ipsum dolor sit amet consectetur adipisicing elit. Commodi, tempora molestiae cum voluptatem voluptates facere sequi laudantium consequatur hic consequuntur nulla recusandae explicabo quae atque, dolores aliquid tenetur reprehenderit nemo.
          Lorem ipsum dolor sit amet consectetur adipisicing elit. Commodi, tempora molestiae cum voluptatem voluptates facere sequi laudantium consequatur hic consequuntur nulla recusandae explicabo quae atque, dolores aliquid tenetur reprehenderit nemo.
          Lorem ipsum dolor sit amet consectetur adipisicing elit. Commodi, tempora molestiae cum voluptatem voluptates facere sequi laudantium consequatur hic consequuntur nulla recusandae explicabo quae atque, dolores aliquid tenetur reprehenderit nemo.
          Lorem ipsum dolor sit amet consectetur adipisicing elit. Commodi, tempora molestiae cum voluptatem voluptates facere sequi laudantium consequatur hic consequuntur nulla recusandae explicabo quae atque, dolores aliquid tenetur reprehenderit nemo.
          Lorem ipsum dolor sit amet consectetur adipisicing elit. Commodi, tempora molestiae cum voluptatem voluptates facere sequi laudantium consequatur hic consequuntur nulla recusandae explicabo quae atque, dolores aliquid tenetur reprehenderit nemo.
          Lorem ipsum dolor sit amet consectetur adipisicing elit. Commodi, tempora molestiae cum voluptatem voluptates facere sequi laudantium consequatur hic consequuntur nulla recusandae explicabo quae atque, dolores aliquid tenetur reprehenderit nemo.
          Lorem ipsum dolor sit amet consectetur adipisicing elit. Commodi, tempora molestiae cum voluptatem voluptates facere sequi laudantium consequatur hic consequuntur nulla recusandae explicabo quae atque, dolores aliquid tenetur reprehenderit nemo.
          Lorem ipsum dolor sit amet consectetur adipisicing elit. Commodi, tempora molestiae cum voluptatem voluptates facere sequi laudantium consequatur hic consequuntur nulla recusandae explicabo quae atque, dolores aliquid tenetur reprehenderit nemo.
          Lorem ipsum dolor sit amet consectetur adipisicing elit. Commodi, tempora molestiae cum voluptatem voluptates facere sequi laudantium consequatur hic consequuntur nulla recusandae explicabo quae atque, dolores aliquid tenetur reprehenderit nemo.
          Lorem ipsum dolor sit amet consectetur adipisicing elit. Commodi, tempora molestiae cum voluptatem voluptates facere sequi laudantium consequatur hic consequuntur nulla recusandae explicabo quae atque, dolores aliquid tenetur reprehenderit nemo.
          Lorem ipsum dolor sit amet consectetur adipisicing elit. Commodi, tempora molestiae cum voluptatem voluptates facere sequi laudantium consequatur hic consequuntur nulla recusandae explicabo quae atque, dolores aliquid tenetur reprehenderit nemo.
          Lorem ipsum dolor sit amet consectetur adipisicing elit. Commodi, tempora molestiae cum voluptatem voluptates facere sequi laudantium consequatur hic consequuntur nulla recusandae explicabo quae atque, dolores aliquid tenetur reprehenderit nemo.
          Lorem ipsum dolor sit amet consectetur adipisicing elit. Commodi, tempora molestiae cum voluptatem voluptates facere sequi laudantium consequatur hic consequuntur nulla recusandae explicabo quae atque, dolores aliquid tenetur reprehenderit nemo.
          Lorem ipsum dolor sit amet consectetur adipisicing elit. Commodi, tempora molestiae cum voluptatem voluptates facere sequi laudantium consequatur hic consequuntur nulla recusandae explicabo quae atque, dolores aliquid tenetur reprehenderit nemo.
          Lorem ipsum dolor sit amet consectetur adipisicing elit. Commodi, tempora molestiae cum voluptatem voluptates facere sequi laudantium consequatur hic consequuntur nulla recusandae explicabo quae atque, dolores aliquid tenetur reprehenderit nemo.
          Lorem ipsum dolor sit amet consectetur adipisicing elit. Commodi, tempora molestiae cum voluptatem voluptates facere sequi laudantium consequatur hic consequuntur nulla recusandae explicabo quae atque, dolores aliquid tenetur reprehenderit nemo.
          Lorem ipsum dolor sit amet consectetur adipisicing elit. Commodi, tempora molestiae cum voluptatem voluptates facere sequi laudantium consequatur hic consequuntur nulla recusandae explicabo quae atque, dolores aliquid tenetur reprehenderit nemo.
          Lorem ipsum dolor sit amet consectetur adipisicing elit. Commodi, tempora molestiae cum voluptatem voluptates facere sequi laudantium consequatur hic consequuntur nulla recusandae explicabo quae atque, dolores aliquid tenetur reprehenderit nemo.
          Lorem ipsum dolor sit amet consectetur adipisicing elit. Commodi, tempora molestiae cum voluptatem voluptates facere sequi laudantium consequatur hic consequuntur nulla recusandae explicabo quae atque, dolores aliquid tenetur reprehenderit nemo.
          Lorem ipsum dolor sit amet consectetur adipisicing elit. Commodi, tempora molestiae cum voluptatem voluptates facere sequi laudantium consequatur hic consequuntur nulla recusandae explicabo quae atque, dolores aliquid tenetur reprehenderit nemo.
          Lorem ipsum dolor sit amet consectetur adipisicing elit. Commodi, tempora molestiae cum voluptatem voluptates facere sequi laudantium consequatur hic consequuntur nulla recusandae explicabo quae atque, dolores aliquid tenetur reprehenderit nemo.
          Lorem ipsum dolor sit amet consectetur adipisicing elit. Commodi, tempora molestiae cum voluptatem voluptates facere sequi laudantium consequatur hic consequuntur nulla recusandae explicabo quae atque, dolores aliquid tenetur reprehenderit nemo.
          Lorem ipsum dolor sit amet consectetur adipisicing elit. Commodi, tempora molestiae cum voluptatem voluptates facere sequi laudantium consequatur hic consequuntur nulla recusandae explicabo quae atque, dolores aliquid tenetur reprehenderit nemo.
          Lorem ipsum dolor sit amet consectetur adipisicing elit. Commodi, tempora molestiae cum voluptatem voluptates facere sequi laudantium consequatur hic consequuntur nulla recusandae explicabo quae atque, dolores aliquid tenetur reprehenderit nemo.
          Lorem ipsum dolor sit amet consectetur adipisicing elit. Commodi, tempora molestiae cum voluptatem voluptates facere sequi laudantium consequatur hic consequuntur nulla recusandae explicabo quae atque, dolores aliquid tenetur reprehenderit nemo.
          Lorem ipsum dolor sit amet consectetur adipisicing elit. Commodi, tempora molestiae cum voluptatem voluptates facere sequi laudantium consequatur hic consequuntur nulla recusandae explicabo quae atque, dolores aliquid tenetur reprehenderit nemo.
          Lorem ipsum dolor sit amet consectetur adipisicing elit. Commodi, tempora molestiae cum voluptatem voluptates facere sequi laudantium consequatur hic consequuntur nulla recusandae explicabo quae atque, dolores aliquid tenetur reprehenderit nemo.
          Lorem ipsum dolor sit amet consectetur adipisicing elit. Commodi, tempora molestiae cum voluptatem voluptates facere sequi laudantium consequatur hic consequuntur nulla recusandae explicabo quae atque, dolores aliquid tenetur reprehenderit nemo.
          Lorem ipsum dolor sit amet consectetur adipisicing elit. Commodi, tempora molestiae cum voluptatem voluptates facere sequi laudantium consequatur hic consequuntur nulla recusandae explicabo quae atque, dolores aliquid tenetur reprehenderit nemo.
          Lorem ipsum dolor sit amet consectetur adipisicing elit. Commodi, tempora molestiae cum voluptatem voluptates facere sequi laudantium consequatur hic consequuntur nulla recusandae explicabo quae atque, dolores aliquid tenetur reprehenderit nemo.
          Lorem ipsum dolor sit amet consectetur adipisicing elit. Commodi, tempora molestiae cum voluptatem voluptates facere sequi laudantium consequatur hic consequuntur nulla recusandae explicabo quae atque, dolores aliquid tenetur reprehenderit nemo.
          Lorem ipsum dolor sit amet consectetur adipisicing elit. Commodi, tempora molestiae cum voluptatem voluptates facere sequi laudantium consequatur hic consequuntur nulla recusandae explicabo quae atque, dolores aliquid tenetur reprehenderit nemo.
          Lorem ipsum dolor sit amet consectetur adipisicing elit. Commodi, tempora molestiae cum voluptatem voluptates facere sequi laudantium consequatur hic consequuntur nulla recusandae explicabo quae atque, dolores aliquid tenetur reprehenderit nemo.
          Lorem ipsum dolor sit amet consectetur adipisicing elit. Commodi, tempora molestiae cum voluptatem voluptates facere sequi laudantium consequatur hic consequuntur nulla recusandae explicabo quae atque, dolores aliquid tenetur reprehenderit nemo.
          Lorem ipsum dolor sit amet consectetur adipisicing elit. Commodi, tempora molestiae cum voluptatem voluptates facere sequi laudantium consequatur hic consequuntur nulla recusandae explicabo quae atque, dolores aliquid tenetur reprehenderit nemo.
          Lorem ipsum dolor sit amet consectetur adipisicing elit. Commodi, tempora molestiae cum voluptatem voluptates facere sequi laudantium consequatur hic consequuntur nulla recusandae explicabo quae atque, dolores aliquid tenetur reprehenderit nemo.
          Lorem ipsum dolor sit amet consectetur adipisicing elit. Commodi, tempora molestiae cum voluptatem voluptates facere sequi laudantium consequatur hic consequuntur nulla recusandae explicabo quae atque, dolores aliquid tenetur reprehenderit nemo.
          Lorem ipsum dolor sit amet consectetur adipisicing elit. Commodi, tempora molestiae cum voluptatem voluptates facere sequi laudantium consequatur hic consequuntur nulla recusandae explicabo quae atque, dolores aliquid tenetur reprehenderit nemo.
          Lorem ipsum dolor sit amet consectetur adipisicing elit. Commodi, tempora molestiae cum voluptatem voluptates facere sequi laudantium consequatur hic consequuntur nulla recusandae explicabo quae atque, dolores aliquid tenetur reprehenderit nemo.
          Lorem ipsum dolor sit amet consectetur adipisicing elit. Commodi, tempora molestiae cum voluptatem voluptates facere sequi laudantium consequatur hic consequuntur nulla recusandae explicabo quae atque, dolores aliquid tenetur reprehenderit nemo.
          Lorem ipsum dolor sit amet consectetur adipisicing elit. Commodi, tempora molestiae cum voluptatem voluptates facere sequi laudantium consequatur hic consequuntur nulla recusandae explicabo quae atque, dolores aliquid tenetur reprehenderit nemo.
          
        </p>
      </section>
    </div>
  );
}
